echo "Installing SQL Express"
start /wait %1 /Action="Install" /IACCEPTSQLSERVERLICENSETERMS /Q /INSTANCENAME=SQLExpress /SECURITYMODE=SQL /SAPWD="%2" /TCPENABLED=1 /BROWSERSVCSTARTUPTYPE=Automatic /SQLSVCSTARTUPTYPE=Automatic /SQLSVCACCOUNT="NT AUTHORITY\Network Service" /SQLSYSADMINACCOUNTS="BUILTIN\ADMINISTRATORS" /AGTSVCACCOUNT="NT AUTHORITY\Network Service"
echo %ERRORLEVEL%
